spring.datasource.url=jdbc:postgresql://db.ufaoqtxzqwvagqpkkumk.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=rCMaV7B59GlEUKhV
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.data-source-properties.sslmode=require